CFLAGS = -D_REENTRANT -g -Wall  -std=gnu99 -Wno-unused-function 

ice_cream_store: ice_cream_store.c
	gcc ice_cream_store.c $(CFLAGS) -lnsl -lpthread ./libthread_107.a ./librssnews.a

student_examination: student_examination.c
	gcc student_examination.c $(CFLAGS) -lnsl -lpthread ./libthread_107.a ./librssnews.a

official_solution: official_solution.c
	gcc official_solution.c $(CFLAGS) -lnsl -lpthread ./libthread_107.a ./librssnews.a
